language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install build-essential git
  - sudo apt-get install libopenblas-dev
  - sudo apt install libomp-dev

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - python -m unittest tests/simple_test.py
