{% set name = "cpnet" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: c95f6db3c35972de29faf5c772404ae289c6c53e2175a96c144e1aefa4b9bd15

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - joblib >=0.16.0
    - networkx >=2.0
    - numba
    - numpy >=1.16.0
    - pandas >=1.1.0
    - pip
    - plotly >=4.10.0
    - python
    - scipy >=1.5.2
    - seaborn >=0.11.0
    - simanneal >=0.4.2
    - tqdm
  run:
    - joblib >=0.16.0
    - networkx >=2.0
    - numba
    - numpy >=1.16.0
    - pandas >=1.1.0
    - plotly >=4.10.0
    - python
    - scipy >=1.5.2
    - seaborn >=0.11.0
    - simanneal >=0.4.2
    - tqdm

test:
  imports:
    - cpnet

about:
  home: "https://github.com/skojaku/core-periphery-detection"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Algorithm for finding multiple core-periphery pairs in networks"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
